services:
  mysql:
    image: mysql:8.0
    container_name: thn_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: nat_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - thn_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p12345678"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: thn_redis
    restart: always
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - thn_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: thn_be_app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/nat_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: password
      SPRING_REDIS_DATABASE: 0
    ports:
      - "8080:8080"
    networks:
      - thn_network

volumes:
  mysql_data:
  redis_data:

networks:
  thn_network: